channels:
  - pytorch
  - conda-forge
  - anaconda
  - oxfordcontrol
  - defaults
dependencies:
  - python=3.5
  - numpy
  - pytorch
  - pillow
  - pandas
  - matplotlib
  - torchvision
  - mesa-libgl-cos6-x86_64
  - opencv
  - pip:
    - sk-video
    - utils

